kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    helm.sh/resource-policy: "keep"
    meta.helm.sh/release-name: "{{ $.Release.Name }}"
    meta.helm.sh/release-namespace: "{{ $.Release.Namespace }}"
  name: omada-data
  labels:
    app: omada-data
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
  storageClassName: local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    helm.sh/resource-policy: "keep"
    meta.helm.sh/release-name: "{{ $.Release.Name }}"
    meta.helm.sh/release-namespace: "{{ $.Release.Namespace }}"
  name: omada-work
  labels:
    app: omada-work
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
  storageClassName: local-path
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    helm.sh/resource-policy: "keep"
    meta.helm.sh/release-name: "{{ $.Release.Name }}"
    meta.helm.sh/release-namespace: "{{ $.Release.Namespace }}"
  name: omada-logs
  labels:
    app: omada-logs
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: local-path
